### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by kkkdaxu** [zengjianquan/CPP_STLAndGenericProgramming#1]
lz的笔记做的超级好哇，对我的学习很有帮助，极大提高了听侯捷老师课程的效率，不知道楼主后面的视频还有做笔记嘛，可以麻烦更新下不～

**Comment by zengjianquan** [comment]
感谢支持，对您的学习有帮助就好 🙂
因为后面的视频其实剩的不多，还有就是一些工作时间安排以及在看其他系列视频的原因（懒），所以我这边就没有去深入的看和研究了。😓
不过还是会去做更新的，既然您都这么夸赞这些笔记了~ 这周末会抽空看并且更新的。
最后再次感谢~ 😄

**Comment by kkkdaxu** [comment]
好滴好滴，谢谢lz
也祝工作顺利～

**Comment by zengjianquan** [comment]
剩余部分更新完毕🙂
issue 就先关闭了
